; PlatformIO Project Configuration File

[env:esp32-s3-devkitc-1]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600

build_flags =
	-DCAMERA_MODEL_ESP32S3_EYE
	-DBOARD_HAS_PSRAM
	-I include
